language: python

sudo: false

notifications:
   email: false

env:
  global:
    secure: A+LEoLUab6uufvDD9WdMh5b3lnjq65AAJAm+pUO30hl39ewQJEMZKg//8fP1xder9x4Yl6XeEGjRX09XDMUTL3y9dKDWok7e/B1OthZKMORbrMuj0KY9piKgHQ7SnDKR7Q3IWpqkkxUtZX/UcK+EyPQZstxIGJRGEdibCEcKpQK4f26wKATOkJ4FKBchsXKf/68JIRfF/yRY6VTErinCTrYAfjl3ZPYk+aER3ukLPz8yG3x48b9Q0uxjDkQiQXeffyfl2niQMtf93xJ8R3H2ohNjmssy3fwxKUaqWMntgiGG3HjWd1zP3dWBuHUDF7pQTA/S3ESeA9Dx1MYrsjDgjmBwvw9Bl+czzBAkaaw4mNNoyiN76ntNUWDfbIk09MBlvE1vRvQPBdxKJ9QWBJt3bSY7+K4yuNZCVWYiVlioS0pHIyCyHL1oOD6q24uvswISBddnDWR+wG+g4tsILo2nYDqqfLVMHyL22m3CwVAzvs4kVWZHf/3xdQb2cstA43D+wvYNp/HdtpowLsJXbuPNnm1jx3SPiunOOC9crUK6NsXuLLw5USPWlRwdRzE5zsqKXiY3Y5gkrdSmZ5qRHSX9PthT/88iub2aBzYumoaos15arJKGWsdKkl4STNJMGjog2Mv9M46UkpR45tNXpYt9Y1OXa0Zb/01jb7wr44z9CqU=

#For Pypandoc can work, pandoc needs to be installed
addons:
  apt_packages:
    - pandoc

python:
  - 3.5

before_install:
  - pip install -U pip
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter # Code Climate coverage
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# command to install dependencies
install:
  - pip install -r requirements.txt
  - python setup.py install

# commands to run tests
script:
  - coverage run --source=charpy.app -m unittest
  - coverage xml # For Codacy

after_success:
  - pip install charpy
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT    # Code Climate code coverage
  - codecov                                                           # Codecov code coverage
  - python-codacy-coverage -r coverage.xml                            # Codacy code coverage